spring:
  application:
    name: exchange-checker

giphy-api-key: fHaPkumnxrfb5JoPB1r3PmEvs7rzWIu7
openexchangerates-api-key: 27f7301e074543518cdc3ed2d8821676

tag-broke: broke
tag-rich: rich

feign:
  exchange-rates-name: "exchange-rates"
  exchange-rates-url: "https://openexchangerates.org/api/"
  giphy-name: "giphy"
  giphy-url: "https://api.giphy.com/v1/"